### ISSUE TITLE
Is there any way to remove the face restriction from the application?

### ISSUE THREAD

**Issue by kjanjua26** [google/basicbokeh#2]
I am unable to visualize the images that have no faces in them (i.e. no face detected). I wanted to remove that restriction from the app. I have switched to rear cameras, but it still requires the face detection. Any tips on how to do that?
I am able to save the two images separately as well.

Thanks.

**Comment by kjanjua26** [comment]
So, I have tried editing the parameters in `StillCaptureSessionCallback.kt`. 
I set the following parameters:

```
twoLens.wideShotDone = true
twoLens.normalShotDone = true
twoLens.normalParams = MainActivity.cameraParams.get(normalLensId) ?: params
twoLens.wideParams = MainActivity.cameraParams.get(wideAngleId) ?: params
twoLens.normalParams.hasFace = true
twoLens.normalParams.faceBounds = params.faceBounds
twoLens.normalParams.expandedFaceBounds = params.expandedFaceBounds
twoLens.wideParams.hasFace = true
twoLens.wideParams.faceBounds = params.faceBounds
twoLens.wideParams.expandedFaceBounds = params.expandedFaceBounds
```
I set the `.hasFace` parameter to `true` regardless of face detection. Now sometimes it works (i.e. captures picture without the face from both wide angle and normal), and sometime it doesn't, which is weird. Does it have something to do with callback? 
**This is how it looks when the face is not detected:**
<a href="https://ibb.co/wBxn7Fp"><img src="https://i.ibb.co/xXRnYtz/Normal-Shot-IMG-20190624-152437.jpg" alt="Normal-Shot-IMG-20190624-152437" border="0"></a>
**Same parameters, no change, on next capture, it worked.**
<a href="https://ibb.co/b38XVg6"><img src="https://i.ibb.co/Mh37HDg/Normal-Shot-IMG-20190624-152400.jpg" alt="Normal-Shot-IMG-20190624-152400" border="0"></a>

Any suggestions regarding what is causing this?

**Comment by emilieroberts** [comment]
Hi, thanks for the question and follow up. To make sure I understand: you are doing a dual-cam capture and when there is not a face in the capture, it is not working?
- do you have grab-cut enabled?
- are the saved images correct? Or both preview and saved images?
- are you capturing at maximum image size?

I'm not sure exactly what is causing this, my hunch is that facebounds is encompassing the whole picture and masking it all in. I have a couple of ideas to get this working depending on if you want face detect sometimes or not:

In Camera2Controller, you could comment out the face_detect_mode section here:
```
 // Request face detection
            if (CameraMetadata.STATISTICS_FACE_DETECT_MODE_OFF != params.bestFaceDetectionMode)
                params.captureBuilder?.set(CaptureRequest.STATISTICS_FACE_DETECT_MODE, params.bestFaceDetectionMode)
            Logd("FACE-DETECT DEBUG: I am setting face-detect mode to: " + params.bestFaceDetectionMode)
```

Digging deeper, in the DoBokeh function in BokehEffect.kt, there is only one face specific bit:
```
if (twoLens.normalParams.hasFace)
..
```
This will mask in the face so it is always included in the "foreground". It depends on the faceBounds for this (specifically from the "normalLens"). If faceBounds includes everything, everything will be included. You could comment this part out completely to remove face masking in.

Another approach, in onCaptureCompleted in the StillCaptureSessionCallback.kt file, is all the face detect logic for the captured images. Looking at my logic it looks like I use the faces from the first image received - so your varied results might be because sometimes different cameras return first. One of them may be returning different faceBounds or if the image sizes are very different, if the largest image comest back first, it may be that the expanded bounds cover the entire smallest images. If you want to disable face detection, modify the following section:
```
twoLens.normalParams.hasFace = params.hasFace
twoLens.normalParams.faceBounds = params.faceBounds
twoLens.normalParams.expandedFaceBounds = params.expandedFaceBounds
twoLens.wideParams.hasFace = params.hasFace
twoLens.wideParams.faceBounds = params.faceBounds
twoLens.wideParams.expandedFaceBounds = params.expandedFaceBounds
```
And set the hasFace variables to false. This should skip any masking in in the DoBokeh function.

Hope that helps!

**Comment by kjanjua26** [comment]
Hey, thanks for getting back. Just to answer your questions
1. No, I am not using grab cut. 
2. No, the saved images are not correct either.
3. I tried all the JPEG quality sizes listed in the preference menu, observed the same result for all.

I tried your suggestions. In `doBokeh()` in `BokehEffect.kt`, I had to comment out the entire stereo chunk since it caused dual cam capture to crash (I didn't debug it since that was not required at the moment). Furthermore, I did comment out the `Camera2Controller.kt` chunk where the face detection is requested. Similarly, I set the variable `.hasFace = false` for both the wide and normal. So, here are the effects of these changes.

1. Now the face restriction is gone, but it works at a certain level of closeness to the object of interest. I am looking to capture generic scene images. Here is what I mean.
<a href="https://ibb.co/hCqY9z4"><img src="https://i.ibb.co/CWrP8GY/Wide-Shot-IMG-20190625-125244.jpg" alt="Wide-Shot-IMG-20190625-125244" border="0"></a>

2. Generic scenes are not captured and I get the same masked bitmap as output (saved and preview).
Do you think this is because of some focus lock? Does exposure has something to do with this?

Once again, thanks for your response. 
Also since the `README.md` mentions in next steps to check if multi-camera works on back cameras, I can confirm that it works on Huawei Mate20 Pro's back cameras.

**Comment by kjanjua26** [comment]
Thanks for the help.
